name: Build and Deploy

on:
  push:
    branches: [new]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
        env:
          REACT_APP_STARSWAP_BOOST: ${{ secrets.BOOST }}
          REACT_APP_INFURA_KEY: '538f147a2d66487d86f0a2fcc2afdcb5'
          CI: false

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'new.starswap.xyz'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          SOURCE_DIR: 'build'
